# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/miuicamera/common

PRODUCT_COPY_FILES += \
    vendor/miuicamera/common/proprietary/system/addon.d/addond_head:$(TARGET_COPY_OUT_SYSTEM)/addon.d/addond_head \
    vendor/miuicamera/common/proprietary/system/addon.d/addond_tail:$(TARGET_COPY_OUT_SYSTEM)/addon.d/addond_tail \
    vendor/miuicamera/common/proprietary/system/etc/default-permissions/miuicamera-permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/default-permissions/miuicamera-permissions.xml \
    vendor/miuicamera/common/proprietary/system/etc/device_features/pyxis.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/device_features/pyxis.xml \
    vendor/miuicamera/common/proprietary/system/etc/permissions/privapp-permissions-miui.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-miui.xml \
    vendor/miuicamera/common/proprietary/system/etc/sysconfig/miuicamera-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/miuicamera-hiddenapi-package-whitelist.xml

PRODUCT_PACKAGES += \
    libCNamaSDK \
    libCameraEffectJNI \
    libDocumentProcess \
    libDollyZoom \
    libFUAuthHelper \
    libFUP2AHelper \
    libSNPE \
    libarc_layer_sgl \
    libarcsoft_wideselfie \
    libcamera_algoup_jni.xiaomi \
    libcamera_ambilight_ambt_qcom \
    libcamera_ambilight_utils_qcom \
    libcamera_arcsoft_beautyshot \
    libcamera_arcsoft_handgesture \
    libcamera_beauty_mpbase \
    libcamera_handgesture_mpbase \
    libcamera_jpegutil_jni.xiaomi \
    libcamera_mialgo_ambilight_qcom \
    libcamera_mianode_jni.xiaomi \
    libcamera_wideselfie_mpbase \
    libclone_c++_shared \
    libcom.xiaomi.camera.requestutil \
    libdoc_photo \
    libdoc_photo_c++_shared \
    libfenshen_snpe \
    libffmpeg \
    libfuai \
    libhandengine.arcsoft \
    libinception_video \
    libjni_arcsoft_beautyshot \
    libjni_wideselfie \
    libmimoji_bokeh_845_video \
    libmimoji_soundsupport \
    libmimoji_tracking \
    libmimoji_video2gif \
    libmiuinative \
    libmorpho_memory_allocator \
    libmorpho_panorama_gp3 \
    libmorpho_sensor_fusion \
    libpta_server \
    librecord_video \
    libsymphony-cpu \
    libvideo_extra_color_converter \
    libvideo_extra_interpolator \
    libvvc++_shared \
    libvvffmpeg \
    libvvmediaeditor \
    libMegviiFacepp-0.5.2 \
    libmegface \
    MiuiCamera \
    MiuiExtraPhoto
